### ISSUE TITLE
Set Request HTTP Header on NewClient

### ISSUE THREAD

**Issue by awylie199** [peppage/foursquarego#4]
Hi,

Thanks very much for creating this project!

I'd like to set the 'Accept-Language' header in an explore request in order to set the locale for FourSquare, as they have some support for [internationalization](https://developer.foursquare.com/overview/versioning) in their responses.

I can see you're using [Sling](https://github.com/dghubble/sling) under the hood of the NewClient method, but the sling member isn't exposed publicly. I'd hope to do something like:

```go
	httpClient := &http.Client{
		Timeout: time.Second * 10,
	}
	params := &foursquarego.VenueExploreParams{...}
	client := foursquarego.NewClient(httpClient, "foursquare", fsClientID, fsClientSecret, "")
	client.Venues.Sling.Set("Accept-Language", "fr")
	venue, _, err := client.Venues.Explore(params)
```

Is there another way to go about this? In the FourSquare docs it says alternatively you can add a parameter, e.g. locale=XXX, but the header is preferred.

Many thanks in advance,
Alex

**Comment by peppage** [comment]
Sure I'll add the ability to add a header

**Comment by awylie199** [comment]
Awesome, thanks very much

**Comment by peppage** [comment]
I created the function and it would have the ability to be used inline,

```go
resp, _, err := c.Venues.SetHeader("Accept-Language", "fr").Explore(&VenueExploreParams{
    LatLong: "40.070679, -89.072332",
})
```

Looks good?

**Comment by awylie199** [comment]
Yeah looks awesome, thanks very much
